[project]
name = "fictool"
description = "Tools to help writers create fictional worlds"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "invoke>=2.2.0",
    "jupyterlab>=4.3.5",
    "matplotlib>=3.10.1",
    "rich>=13.9.4",
    "typer>=0.17.3",
]
dynamic = ["version"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "tox>=4.24.1",
    "sphinx>=8.2.3",
    "ruff>=0.12.11",
    "mypy>=1.18.2",
]

[tool.tox]
requires = ["tox>=4.19"]
env_list = ["3.14", "3.13"]

[tool.tox.env_run_base]
description = "Run test under {base_python}"
deps = ["pytest", "ruff", "mypy"]
commands = [
    ["pytest"],
    ["pytest", "--doctest-modules", "src/fictool"],
    ["ruff", "check", "--ignore", "F401,F841,E741"],
    ["mypy", "src/fictool/dice.py"],
]

[project.scripts]
fiction_tools = "fictool.main:app"

[tool.hatch.version]
path = "src/fictool/main.py"

[tool.hatch.build.targets.wheel]
packages = ["src/fictool"]
